### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dreadkopp** [markusressel/fan2go#12]
Cheers.

First of all: loverly tool, came here due to problems with fancontrol

since i am not familiar with go (yet) i'd like to add some suggestions (maybe a PR later, when i understand go)

sensor-detect:

  - initially step up in increments by 20 to quickly catch starting PWM
  - also do fans one by one to prevent potential overheating from shutting down all the fans @start

control:

  - it would be really nice to combine sensors in some kind of simple logic (median, max, floor(md5(rand())), ...) to i.e configure case fans to ramp up if either gpu or cpu need more cooling

**Comment by markusressel** [comment]
Thank you for the suggestions :+1:

> initially step up in increments by 20 to quickly catch starting PWM

I don't think it matters too much how long it takes to make the initial measurement, since it is a one-time operation. We can add a configuration option for this though and give users a choice.

> also do fans one by one to prevent potential overheating from shutting down all the fans @start

This doesn't prevent systems from shutting down due to overheating issues, if f.ex. there is only a single CPU fan. I don't think there is a way to prevent this other than having the system mostly idle when initializing fan2go, but, again, this is a only a single time operation. So I don't think it is a big issue. When you initialize fans for fancontrol you would have to do the exact same thing.

The way I initially wanted the calibration to work was incremental and ongoing. I wanted to do build a rough estimation for the fan speed curve when initializing, and continuously improve that with live data while fan2go is running. But since it has been working pretty much perfectly with the current approach, I didn't invest the time to implement this.

> it would be really nice to combine sensors in some kind of simple logic (median, max, floor(md5(rand())), ...) to i.e configure case fans to ramp up if either gpu or cpu need more cooling

I totally agree, but I don't have the need or time to implement this. You can definitely open a dedicated issue for tracking this specific feature though and maybe it will be implemented by someone (maybe even you) in the future.
